name: gcoin
description: "developed by attech."
publish_to: 'none'
#version: 0.2.3+16
version: 0.1.5+12

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  get: ^4.7.2
  get_storage: ^2.1.1
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  cloudflare_turnstile: ^3.3.1 # Use the latest version from pub.dev
  webview_flutter: ^4.7.0
  country_picker: ^2.0.27
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/game/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
