// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGM-SE3xBrBNfsaz0p0gJFVyalnc4Uw2g',
    appId: '1:427914865185:android:3ab5481675de92503ed160',
    messagingSenderId: '427914865185',
    projectId: 'grownetwork-b0208',
    databaseURL: 'https://grownetwork-b0208-default-rtdb.firebaseio.com',
    storageBucket: 'grownetwork-b0208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXvI5yFJk-hSM37BKpPt6ff0J5C2xJInQ',
    appId: '1:427914865185:ios:2d49245c2d4b50103ed160',
    messagingSenderId: '427914865185',
    projectId: 'grownetwork-b0208',
    databaseURL: 'https://grownetwork-b0208-default-rtdb.firebaseio.com',
    storageBucket: 'grownetwork-b0208.firebasestorage.app',
    iosBundleId: 'pro.gnetwork.gnetwork',
  );
}
